BackendBundle\Entity\Producto:
    type: entity
    table: producto
    indexes:
        fk_producto_categoria1_idx:
            columns:
                - categoria_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        tamano:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        precio:
            type: integer
            nullable: true
            options:
                unsigned: false
        descuento:
            type: integer
            nullable: true
            options:
                unsigned: false
        visible:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        categoria:
            targetEntity: Categoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
