BackendBundle\Entity\Reserva:
    type: entity
    table: reserva
    indexes:
        fk_reserva_usuario1_idx:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        comprobante:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        fechaEmision:
            type: datetime
            nullable: true
            column: fecha_emision
        fechaActualizacion:
            type: datetime
            nullable: true
            column: fecha_actualizacion
        precioTotal:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: precio_total
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
